---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME_SCANFILE
  labels:
    app: $SERVICE_NAME_SCANFILE
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: $SERVICE_NAME_SCANFILE
  template:
    metadata:
      name: $SERVICE_NAME_SCANFILE
      labels:
        app: $SERVICE_NAME_SCANFILE
        tier: web
    spec:
      containers:
        - name: $SERVICE_NAME_SCANFILE
          image: $BUILD_IMAGE_SCANFILE
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: $SERVICE_NAME_SCANFILE-environment-variables
          ports:
          - name: web
            containerPort: 3030
          # livenessProbe:
          #   httpGet:
          #     path: /version
          #     port: 3030
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 15
          # readinessProbe:
          #   httpGet:
          #     path: /version
          #     port: 3030
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 3
