# Workflow to build and push the imgages for the schulcloud antivirus service 
# Tagging of the images push to Docker Hub  will follow the branch based naming conventions
# use in sc-app-ci to allow deploying the images on team machines  

name: sc-app-build-push

# Controls when the action will run.
on:
  push:
    branches:
      - develop
      - master
      # release branches are of e.g. release/25.3.0
      - release/[0-9]+.[0-9]+.[0-9]+
      # OPS-1664 naming convention <branch>/<JIRA-Ticket ID>-<Jira_Summary>
      - hotfix/[A-Z]+-[0-9]+-[a-zA-Z0-9]+_[a-zA-Z0-9]+*
      - feature/[A-Z]+-[0-9]+-[a-zA-Z0-9]+_[a-zA-Z0-9]+*
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_push"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # Setting environment variables here make them available for all steps
      AVSCANFILE_REPO: schulcloud-avcheck-scanfile
      AVSCANURL_REPO: schulcloud-avcheck-scanurl
      AVSCANWEBSERVER_REPO: schulcloud-avcheck-webserver
      DOCKER_NAMESPACE: schulcloud
      BRANCH_NAME: ""
      AVCHECK_VERSION: ""
      DOCKER_TAG_POSTFIX: ""
      DOCKER_TAG_SHA: ""
      JIRA_TicketID: ""
      BRANCH_PREFIX: ""

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it must be on first place to allow central setting of working directory
      - uses: actions/checkout@v2
      - name: Read version file
        # The version to be used for tagging the images is read out of the version file
        id: read_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version
      - name: Set env AVCHECK_VERSION
        run: |
          echo "Version of antivirus_service is ${{ steps.read_version.outputs.content }}"
          echo "AVCHECK_VERSION=${{ steps.read_version.outputs.content }}" >> $GITHUB_ENV
      - name: RegEx JIRA ticket ID
        uses: actions-ecosystem/action-regex-match@v2
        id: jira
        with:
          text: ${{ github.ref }}
          regex: '^refs\/heads\/hotfix|feature\/([A-Z]+-[0-9]+)-[a-zA-Z_]+$'
          flags: gm
      - name: Set env var JIRA_TicketID
        run: |
          echo "JIRA_TicketID is ${{ steps.jira.outputs.group1 }}"
          echo JIRA_TicketID=${{ steps.jira.outputs.group1 }} >> $GITHUB_ENV
      - name: Find JIRA ticket BRANCH_PREFIX
        uses: actions-ecosystem/action-regex-match@v2
        id: branch_prefix
        with:
          text: ${{ github.ref }}
          regex: '^refs\/heads\/([a-zA-Z]+)\/[A-Z]+-[0-9]+-[a-zA-Z_]+$'
          flags: gm
      - name: Set env var JIRA BRANCH_PREFIX
        run: |
          echo "BRANCH_PREFIX is ${{ steps.branch_prefix.outputs.group1 }}"
          echo BRANCH_PREFIX=${{ steps.branch_prefix.outputs.group1 }} >> $GITHUB_ENV
      - name: Get Dockertags for branch
        id: tag
        uses: RalfNellesCap/composite_action_dockertag@v1.0.5
        with:
          AVCHECK_VERSION: ${{ env.AVCHECK_VERSION }}
          GIT_SHA: ${{ env.GITHUB_SHA }}
          JIRA_TicketID: ${{ env.JIRA_TicketID }}
          BRANCH_PREFIX: ${{ env.BRANCH_PREFIX }}
      - name: Set Env Vars for Dockertags
        run: |
          echo DOCKER_TAG_POSTFIX=${{ steps.tag.outputs.docker-tag }} >> $GITHUB_ENV
          echo DOCKER_TAG_SHA=${{ steps.tag.outputs.docker-sha }} >> $GITHUB_ENV
      - name: cancel workflow if Dockertag is empty String
        if: ${{ env.DOCKER_TAG_POSTFIX == '' }}
        uses: andymckay/cancel-action@0.2        
      - name: Echo DOCKER_TAG_POSTFIX
        run: echo "DOCKER_TAG_POSTFIX is ${DOCKER_TAG_POSTFIX}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Scanfile
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile.scanfile
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.AVSCANFILE_REPO }}:${{ env.DOCKER_TAG_POSTFIX }}
      - name: Build and push Scanurl
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile.scanurl
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.AVSCANURL_REPO }}:${{env. DOCKER_TAG_POSTFIX}}
      - name: Build and push Webserver
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile.webserver
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.AVSCANWEBSERVER_REPO }}:${{ env.DOCKER_TAG_POSTFIX }}
      - name: Build and push SHA Tag for Master and Release on Scanfile
        if: ${{ github.event.inputs.branch-prefix == 'master' || github.event.inputs.branch-prefix == 'release' }}
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile.scanfile
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.AVSCANWEBSERVER_REPO }}:${{ env.DOCKER_TAG_SHA }}
      - name: Build and push SHA Tag for Master and Release on Scanurl
        if: ${{ github.event.inputs.branch-prefix == 'master' || github.event.inputs.branch-prefix == 'release' }}
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile.scanurl
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.AVSCANWEBSERVER_REPO }}:${{ env.DOCKER_TAG_SHA }}
      - name: Build and push SHA Tag for Master and Release on Webserver
        if: ${{ github.event.inputs.branch-prefix == 'master' || github.event.inputs.branch-prefix == 'release' }}
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile.webserver
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.AVSCANWEBSERVER_REPO }}:${{ env.DOCKER_TAG_SHA }}